syntax = 'proto3';

package live_auction;
option java_multiple_files=true;
option java_package="com.live.auction.grpc";
option java_outer_classname="LiveAuctionProto";

import "google/protobuf/timestamp.proto";

enum AuctionStatus {
  ACTIVE = 0;
  FINISHED = 1;
  CANCELED = 2;
}

service LiveAuctionService {
  // Create a new auction - Unary Communication
  rpc CreateAuction(CreateAuctionRequest) returns (AuctionResponse);

  // Retrieves an Auction details - Unary Communication
  rpc GetAuctionDetails(AuctionRequest) returns (AuctionDetailResponse);

  // Streaming response for all the history about auctions
  rpc GetAuctionHistory(AuctionRequest) returns (stream BidHistoryResponse);

  // Lists the LIVE auctions
  rpc GetLiveAuctions(Empty) returns (LiveAuctionList);

  // 1. Enter the room then watch the live auction (Server Streaming)
  rpc WatchAuctionRoom(AuctionRequest) returns (stream LiveAuctionUpdate);

  // 2. Place Bid (Unary)
  rpc PlaceBid(CreateBidRequest) returns (PlaceBidResponse);
}

message Empty {}

message LiveAuctionList {
  repeated AuctionDetailResponse auctionDetail = 1;
}

message CreateBidRequest {
  string auction_id = 1;
  string user_id = 2;
  double amount = 3;
}

message BidResponse {
  string auction_id = 1;
  string leader_name = 2;
  double amount = 3;
  google.protobuf.Timestamp request_time = 4;
  bool is_successful = 5;
  string message = 6;
}

message AuctionRequest {
  string auction_id = 1;
}

message BidHistoryResponse {
  string bidder_name = 1;
  double bid_amount = 2;
  google.protobuf.Timestamp bid_creation_time = 3;
}

message CreateAuctionRequest {
  string title = 1;
  string description = 2;
  double start_price = 3;
  google.protobuf.Timestamp end_time = 4;
}
message AuctionResponse {
  string auction_id = 1;
  AuctionStatus status = 2;
}

message AuctionDetailResponse {
  string auction_id = 1;
  string auction_title = 2;
  string auction_description = 3;
  AuctionStatus status = 4;
  google.protobuf.Timestamp end_time = 5;
  double current_highest_bid = 6;
}

message LiveAuctionUpdate {
  string auction_id = 1;
  string leader_name = 2;
  double new_highest_bid = 3;
  google.protobuf.Timestamp timestamp = 4;
}

message PlaceBidResponse {
  bool is_successful = 1;
  string message = 2;
}